apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
  - ../../base

components:
  - github.com/geekahmed-yt/hello-platform-global-config/components/replicas
  - github.com/geekahmed-yt/hello-platform-global-config/components/resource-limits

patches:
  - path: patches/deployment-patch.yaml
    target:
      kind: Deployment

images:
  - name: hello-health-service
    newName: geekahmed/hello-health-service
    newTag: main-0b5d366

commonLabels:
  environment: staging
