apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-health-service
spec:
  template:
    spec:
      containers:
        - name: hello-health-service
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: ENVIRONMENT
              value: "dev"
            - name: CACHE_ENABLED
              value: "false"
