apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-health-service
spec:
  template:
    spec:
      containers:
        - name: hello-health-service
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
